[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/post/*"
  to = "/blog/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
